### ISSUE TITLE
Problems when training with multiple GPUs

### ISSUE THREAD

**Issue by WYFDUT** [dragonfly606/MonoCD#1]
MonoCD is a really nice work. But I meet some prolems when training.
Whenever I try to train with multiple GPUs, I keep getting:
RuntimeError: cannot reshape tensor of 0 elements into shape [0, 3, -1] because the unspecified dimension size -1 can be any value and is ambiguous
Strangely enough, when I train with a single GPU, I don't get the above error.

I use the following statement for training:
CUDA_VISIBLE_DEVICES=0,1 python tools/plain_train_net.py --num_gpus 2 --batch_size 8 --config runs/monocd.yaml --output output/exp1

**Comment by YuJiXYZ** [comment]
hello， I also try to use this project，but the command that author provided do not work for my computer.
So could you provide the your install command. Thank you!.

**Comment by dragonfly606** [comment]
@WYFDUT thank you for your attention. Actually, I haven't tested the training code on multiple GPUs yet. If possible, please run it on a single GPU first. I will add a multi-GPU training code in the future.

**Comment by WYFDUT** [comment]
> @WYFDUT thank you for your attention. Actually, I haven't tested the training code on multiple GPUs yet. If possible, please run it on a single GPU first. I will add a multi-GPU training code in the future.

Thank you very much, hopefully we can get your code trained on multiple GPUs afterward!

**Comment by WYFDUT** [comment]
> hello， I also try to use this project，but the command that author provided do not work for my computer. So could you provide the your install command. Thank you!.

Perhaps you could describe the details of the problem you meeted.

**Comment by YuJiXYZ** [comment]
ok，I have tried some version of pytorch, but when I use this command：“pip install -r requirements.txt”，I always meet this problem, so could please solve this, thank you!
![image](https://github.com/dragonfly606/MonoCD/assets/106587670/4fc84e15-5b79-4c3d-a2d5-4cbb49c7fa74)

**Comment by WYFDUT** [comment]
> ok，I have tried some version of pytorch, but when I use this command：“pip install -r requirements.txt”，I always meet this problem, so could please solve this, thank you! ![image](https://private-user-images.githubusercontent.com/106587670/325078335-4fc84e15-5b79-4c3d-a2d5-4cbb49c7fa74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTQwOTYsIm5iZiI6MTcxMzk1Mzc5NiwicGF0aCI6Ii8xMDY1ODc2NzAvMzI1MDc4MzM1LTRmYzg0ZTE1LTViNzktNGMzZC1hMmQ1LTRjYmI0OWM3ZmE3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxMDE2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDk0Y2E3ZTVkMTEwMTJlYzI3MjA4NDg5YTI5ODMyYWI0MDAzNDA3ZDM5NDJhYzg3Zjc0OWNhYmEwNTcwODA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ow8gex960lpuVY289QKwyRkOyGRJzNk10rFz0RMaob4)

It seems like your CUDA Version does not match pytorch version. Perhaps you need to install the version of cudatoolkit that corresponds to your Pytorch environment
My GPU is 2080Ti
My torch version is： 
pytorch 1.11.0  with cuda11.3 cudnn8.2.0_0

**Comment by YuJiXYZ** [comment]
> > ok，I have tried some version of pytorch, but when I use this command：“pip install -r requirements.txt”，I always meet this problem, so could please solve this, thank you! ![image](https://private-user-images.githubusercontent.com/106587670/325078335-4fc84e15-5b79-4c3d-a2d5-4cbb49c7fa74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTQwOTYsIm5iZiI6MTcxMzk1Mzc5NiwicGF0aCI6Ii8xMDY1ODc2NzAvMzI1MDc4MzM1LTRmYzg0ZTE1LTViNzktNGMzZC1hMmQ1LTRjYmI0OWM3ZmE3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxMDE2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDk0Y2E3ZTVkMTEwMTJlYzI3MjA4NDg5YTI5ODMyYWI0MDAzNDA3ZDM5NDJhYzg3Zjc0OWNhYmEwNTcwODA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ow8gex960lpuVY289QKwyRkOyGRJzNk10rFz0RMaob4)
> 
> It seems like your CUDA Version does not match pytorch version. Perhaps you need to install the version of cudatoolkit that corresponds to your Pytorch environment My GPU is 2080Ti My torch version is： pytorch 1.11.0 with cuda11.3 cudnn8.2.0_0

Ok, I have tried this version, but I still meet this same problem when I use "sh make.sh". So I think this issue may be located in /MonoCD/model/backbone/DCNv2/setup.py, but I do not know how to change this, thank you!

**Comment by WYFDUT** [comment]
> > > ok，I have tried some version of pytorch, but when I use this command：“pip install -r requirements.txt”，I always meet this problem, so could please solve this, thank you! ![image](https://private-user-images.githubusercontent.com/106587670/325078335-4fc84e15-5b79-4c3d-a2d5-4cbb49c7fa74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTQwOTYsIm5iZiI6MTcxMzk1Mzc5NiwicGF0aCI6Ii8xMDY1ODc2NzAvMzI1MDc4MzM1LTRmYzg0ZTE1LTViNzktNGMzZC1hMmQ1LTRjYmI0OWM3ZmE3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxMDE2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDk0Y2E3ZTVkMTEwMTJlYzI3MjA4NDg5YTI5ODMyYWI0MDAzNDA3ZDM5NDJhYzg3Zjc0OWNhYmEwNTcwODA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ow8gex960lpuVY289QKwyRkOyGRJzNk10rFz0RMaob4)
> > 
> > 
> > It seems like your CUDA Version does not match pytorch version. Perhaps you need to install the version of cudatoolkit that corresponds to your Pytorch environment My GPU is 2080Ti My torch version is： pytorch 1.11.0 with cuda11.3 cudnn8.2.0_0
> 
> Ok, I have tried this version, but I still meet this same problem when I use "sh make.sh". So I think this issue may be located in /MonoCD/model/backbone/DCNv2/setup.py, but I do not know how to change this, thank you!

You can try [https://github.com/lucasjinreal/DCNv2_latest]( https://github.com/lucasjinreal/DCNv2_latest) for latest version of deformable convolution installation.

**Comment by dragonfly606** [comment]
Sorry @WYFDUT , I'm a little busy lately and thank you for your waiting. According to reminder in #3 , this issue may not be caused by training with multiple GPUs rather than the small batch size. I have updated training code to avoid this situation.
