### ISSUE TITLE
推理脚本

### ISSUE THREAD

**Issue by qgq99** [dragonfly606/MonoCD#2]
非常感谢作者这篇优秀的工作！ 请问作者能否提供一下推理的脚本呢🤣

**Comment by dragonfly606** [comment]
Hi @qgq99, thank you for your attention. The inference script can be found [here](https://github.com/dragonfly606/MonoCD#:~:text=The%20model%20will%20be%20evaluated%20periodically%20during%20training%20and%20you%20can%20also%20evaluate%20an%20already%20trained%20checkpoint%20with)
`CUDA_VISIBLE_DEVICES=0 python tools/plain_train_net.py --config runs/monocd.yaml --ckpt YOUR_CKPT  --eval
`

**Comment by qgq99** [comment]
> Hi @qgq99, thank you for your attention. The inference script can be found [here](https://github.com/dragonfly606/MonoCD#:~:text=The%20model%20will%20be%20evaluated%20periodically%20during%20training%20and%20you%20can%20also%20evaluate%20an%20already%20trained%20checkpoint%20with) `CUDA_VISIBLE_DEVICES=0 python tools/plain_train_net.py --config runs/monocd.yaml --ckpt YOUR_CKPT --eval `

thanks a lot！
