### ISSUE TITLE
Experiment using Nuscenes Dataset

### ISSUE THREAD

**Issue by jesslyn1999** [dragonfly606/MonoCD#5]
Hi, first of all, thank you for the great work and findings, mainly in using global clues to more accurately predict depth.
I read the paper, specifically on Table.5, it points out that the experiment towards the NuScenes Dataset is also conducted. It would be so helpful for further exploration if the team could add the codes that support the NuScenes dataset experiment.

Thanks! 

<img width="439" alt="Screenshot 2024-06-06 at 6 23 25 PM" src="https://github.com/dragonfly606/MonoCD/assets/36306615/f55cfe74-9b7d-4841-be7f-abae3dc31917">

**Comment by jesslyn1999** [comment]
I have no clue of how to get the road plane equation from the Nuscenes Dataset. Hoping for more insight...

<img width="455" alt="image" src="https://github.com/dragonfly606/MonoCD/assets/36306615/873adc7e-e52a-4fa5-af9e-a3c347f85eb1">

**Comment by dragonfly606** [comment]
Hi @jesslyn1999 , thank you for your attention to our work. The main purpose of Table 5 is to demonstrate the generalization of our method. The evaluation results on the NuScenes dataset are obtained by the model we trained on the KITTI dataset, so we did not utilize the ground plane equation of the Nuscenes dataset. To get the ground plane equation for a dataset you can refer to https://github.com/kujason/avod/issues/19. Apart from this, a simpler alternative is to use the 3D coordinates of all objects in an image for fitting (when the number of objects is more than three) and use a fixed ground plane equation y=1.562 (when the number of objects is less than three).

**Comment by jesslyn1999** [comment]
oh I got it, thank you so much ! @dragonfly606
